import Head from 'next/head';
import { Inter } from '@next/font/google';
import styled from 'styled-components';
import LinkButton from '@/components/Button';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Alexei Belozertcev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomeWrapper>
       <HomeSection>
          <span className='home-section_profession'>About me:</span>
          <h1>Hi! My name is Alexei, let me introduce myself.</h1>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloribus praesentium doloremque adipisci odit corporis ratione voluptatum cupiditate ducimus veniam maxime. Maiores unde impedit, dolorum praesentium laborum similique tempora quasi dolor.</p>
          <Buttons>
        <LinkButton
          link='/'
          bgColor='#E81224' 
          border='2px solid #111827'
          content='LinkedIn' />
        <LinkButton
          link='/'
          bgColor='#E81224' 
          border='2px solid #111827'
          content='Projects' />
       </Buttons>
       </HomeSection>
       
      </HomeWrapper>
    </>
  )
};

const HomeWrapper = styled.div`
  display: grid;
  justify-content: center;
  grid-template-columns: 1fr;
  width: 100%;
  margin: 0 20px;
`;

const HomeSection = styled.div`
  display: flex;
  flex-direction: column;
  gap: 16px;

  .home-section_profession {
    z-index: 1;
    font-family: 'Inter', sans-serif;
    font-style: normal;
    font-weight: 400;
    font-size: 16px;
    line-height: 27px;
    text-transform: uppercase;
    color:  #E81224;
  }

  p {
    font-family: 'Inter';
    font-style: normal;
    font-weight: 400;
    font-size: 24px;
    line-height: 150%;
    color: #111827;
  }

  h1 {
    font-family: 'Righteous', cursive;
    font-style: normal;
    font-weight: 700;
    font-size: 64px;
    line-height: 1em;
    color: #1B1B18;
  }

  h2 {

  }
`;

export const Buttons = styled.div`
  display: flex;
  flex-direction: row;
  gap: 24px;
`;

